#!/usr/bin/perl;
##################################################
#
# Perl::Tk script generated by Visual Camel 0.0.2.2
#
##################################################
use warnings;
use strict;
use Tk;

my $mw = MainWindow->new( -width => '300', -relief => 'ridge', -height => '150', -title => 'OME Functional Test GUI', );
my $var1 = $mw->Label( -pady => '1', -relief => 'flat', -padx => '1', -state => 'normal', -justify => 'center', -text => 'Server Address', )->place( -x => 10, -y => 13);
my $var2 = $mw->Label( -pady => '1', -relief => 'flat', -padx => '1', -state => 'normal', -justify => 'center', -text => 'Test case file', )->place( -x => 11, -y => 44);
my $var3 = $mw->Label( -pady => '1', -relief => 'flat', -padx => '1', -state => 'normal', -justify => 'center', -text => 'Number of clients', )->place( -x => 12, -y => 79);
my $var4 = $mw->Entry( -width => '20', -relief => 'sunken', -state => 'normal', -justify => 'left', -text => '127.0.0.1', )->place( -x => 126, -y => 12);
my $var5 = $mw->Entry( -width => '20', -relief => 'sunken', -state => 'normal', -justify => 'left', -text => 'test_cases.txt', )->place( -x => 125, -y => 43);
my $var6 = $mw->Entry( -width => '20', -relief => 'sunken', -state => 'normal', -justify => 'left', -text => '8', )->place( -x => 125, -y => 80);
my $var7 = $mw->Button( -pady => '1', -relief => 'raised', -padx => '1', -state => 'normal', -justify => 'center', -text => 'Start test', -command =>\&start_test )->place( -x => 112, -y => 113);

$mw->MainLoop();
##################################################
#
# Perl::Tk script generated by Visual Camel 0.0.2.2
#
##################################################
sub start_test {
	my $server_address = $var4->get();
	my $test_case_file = $var5->get();
	my $number_of_test_clients = $var6->get();
	my $command_to_execute = "/bin/bash ./client_automated_test.sh $server_address $test_case_file $number_of_test_clients";
	print ($command_to_execute);
	system($command_to_execute);
}