#ifndef _SERVER_CONSTANTS_H_
#define _SERVER_CONSTANTS_H_

#include <cstddef>
namespace server_constants
{
// Configuration file related
static const char* CONFIGURATION_FILE = "ome.ini";
// General process related
static const char* CONFIGURATION_FILE_SINGLE_INSTANCE_TCP_PORT = "SINGLE_INSTANCE_TCP_PORT";
static const char* CONFIGURATION_FILE_PROCESS_PRIORITY = "PROCESS_PRIORITY";
static const char* CONFIGURATION_FILE_LOGGER_BUFFER_SIZE = "LOGGER_BUFFER_SIZE";
// Central order book related
static const char* CONFIGURATION_FILE_CENTRAL_ORDER_BOOK_MULTITHREADED_ORDER_MATCHING = "CENTRAL_ORDER_BOOK_MULTITHREADED_ORDER_MATCHING";
static const char* CONFIGURATION_FILE_CENTRAL_ORDER_BOOK_PIN_THREADS_TO_CORES = "CENTRAL_ORDER_BOOK_PIN_THREADS_TO_CORES";
static const char* CONFIGURATION_FILE_CENTRAL_ORDER_BOOK_WORK_QUEUE_SIZE_PER_THREAD = "CENTRAL_ORDER_BOOK_WORK_QUEUE_SIZE_PER_THREAD";
static const char* CONFIGURATION_FILE_CENTRAL_ORDER_BOOK_THREAD_STACK_SIZE = "CENTRAL_ORDER_BOOK_THREAD_STACK_SIZE";
static const char* CONFIGURATION_FILE_CENTRAL_ORDER_BOOK_THREAD_PRIORITY = "CENTRAL_ORDER_BOOK_THREAD_PRIORITY";
static const char* CONFIGURATION_FILE_CENTRAL_ORDER_BOOK_HYPER_THREADING = "CENTRAL_ORDER_BOOK_HYPER_THREADING";

static const char* CONFIGURATION_FILE_SYMBOL_ARRAY = "SYMBOL";
// Fix engine related
static const char* FIX_ENGINE_CONFIG_FILE = "quickfix_server.cfg";
static const char* FIX_ENGINE_LOG_DIRECTORY = "quickfix_log";
static const char* FIX_ENGINE_LOG_BACKUP_DIRECTORY = "old_quickfix_log";
// Others
static const std::size_t SERVER_THREAD_SLEEP_DURATION = 1000;
}

#endif